version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hourly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  
  backend:
    build:
      context: ./hourly
    volumes:
      - ./hourly:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - USE_DOCKER_DB=True


  frontend:
    build:
      context: ./hourly-front
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db_filler:
    build:
      context: ./database_filler



volumes:
  postgres_data:

