version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./hourly
    volumes:
      - ./hourly:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./hourly-front
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
