# Generated by Django 5.0.6 on 2024-06-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=1)),
                ('total_price', models.FloatField()),
                ('currency_total_price', models.CharField(max_length=1)),
                ('nights', models.IntegerField()),
                ('availability_start', models.DateField()),
                ('availability_end', models.DateField()),
                ('rating', models.FloatField()),
                ('size_unit', models.CharField(max_length=5)),
                ('capacity', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('distance_to_sea', models.IntegerField()),
                ('distance_to_sea_unit', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=255)),
                ('link', models.TextField()),
                ('room_image', models.TextField()),
            ],
        ),
    ]
