# Generated by Django 5.0.6 on 2024-07-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='beds',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='availability_end',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='availability_start',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='currency_total_price',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='distance_to_sea_unit',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='link',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='size_unit',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_price',
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
