# Generated by Django 5.0.6 on 2024-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0002_rename_beds_apartment_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='capacity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='distance_to_sea',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
