# Generated by Django 5.0.6 on 2024-07-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0003_alter_apartment_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='room_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='distance_to_sea',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='price',
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_per_day',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_price',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
