# Generated by Django 5.0.6 on 2024-07-12 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0004_rename_room_image_apartment_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='type',
            new_name='room_type',
        ),
    ]
