# Generated by Django 5.0.6 on 2024-07-12 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0005_rename_image_apartment_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='total_price',
        ),
    ]
