# Generated by Django 5.0.6 on 2024-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0007_apartment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.CharField(max_length=255),
        ),
    ]
