# Generated by Django 5.0.6 on 2024-07-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hourly_api', '0008_alter_apartment_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
